apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qrnj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qrnj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0060-app
  name: devfile-sample-qrnj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qrnj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qrnj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-qrnj@sha256:a88d0322bbd5f4a9a8cf89e838b080e55ec91540907edcee8fa6c29119a82bd8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
